### PR TITLE
Executor: reworked SetInsertParamType

### PR DESCRIPTION
**Pull request by AmoebaProtozoa**
Signed-off-by: David <davidyangad@gmail.com>

### What's changed

Reworked SetInsertParamType function in the executor module

### Effects

Now more unit tests can be passed, in particular, the following tests should no longer fail or panic:

- testSuite.TestBatchInsertWithOnDuplicate
- testSuite8.TestShardRowIDBits
- seqTestSuite.TestPrepared
- seqTestSuite.TestPreparedIssue8644
- testSessionSuite.TestAutoIncrementWithRetry
- testSessionSuite.TestLastInsertID
- testSessionSuite.TestPrepareZero
- testSessionSuite.TestPrimaryKeyAutoIncrement

### CODE REVIEW

**Comment by RogueJin** [comment]
according to your codes, should there be any test cases need to be modified?

**Review by pupillord — APPROVED** [review]
LGTM

**Comment by AmoebaProtozoa** [comment]
> according to your codes, should there be any test cases need to be modified?

**Comment by RogueJin** [comment]
LGTM

**Review by RogueJin — APPROVED** [review]
LGTM

**Pull request merged**
